language: python

matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: vivid
    python: '2.7'
  - os: linux
    dist: Xenial
    python: '2.7'
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install git default-jre python-setuptools python-pip  python-dev python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose python-pil  python-imaging python-setuptools unzip ghostscript make gcc g++ zlib1g-dev zlib1g -y
    - sudo pip install bx-python
install: python setup.py install
script:
  - haystack_pipeline -help




