language: python

matrix:
    include:
#        - os: linux
#          dist: trusty
#          python: 2.7
        - os: linux
          dist: Xenial
          python: 2.7
#        - os: osx
#          osx_image: xcode7.3
#          language: generic
#          env: TOXENV=py27
#        - os: osx
#          osx_image: xcode8.3
#          language: generic
#          env: TOXENV=py27


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install default-jre -y
  - chmod +x ./.travis/travis_before_install.sh
  - ./.travis/travis_before_install.sh
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update --all --yes
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION ghostscript meme bedtools sambamba ucsc-bigwigaverageoverbed ucsc-bedgraphtobigwig setuptools bx-python numpy scipy matplotlib  jinja2  pandas  pybedtools tqdm
  - pip install weblogo

install: python setup.py install

cache:
  directories:
  - $HOME/download #  add miniconda.sh to TRAVIS cache.
  - $HOME/miniconda2

script:
  - haystack_hotspots -h
  - haystack_download_genome hg19 --yes
  - haystack_run_test
