language: python

matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: vivid
    python: '2.7'
  - os: linux
    dist: Xenial
    python: '2.7'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install default-jre -y
  - chmod +x ./.travis/travis_before_install.sh
  - ./.travis/travis_before_install.sh
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update --all --yes
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION bx-python ghostscript=9.10 numpy scipy matplotlib argparse jinja2 nose dateutil pandas setuptools pil ipython unzip pybedtools pysam meme samtools bedtools sambamba ucsc-bigwigaverageoverbed ucsc-bedgraphtobigwig

install: python setup.py install

cache:
  directories:
  - $HOME/haystack_dependencies
  - $HOME/download #  add miniconda.sh to TRAVIS cache.
  - $HOME/miniconda2

script:
  - haystack_hotspots -h
  - haystack_download_genome hg19
  - cd $HOME/haystack_dependencies
  - haystack_pipeline test_data/samples_names_genes.txt hg19 --output_directory $HOME/OUTPUT --bin_size 200 --chrom_exclude 'chr(?!21)'
