language: python

matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: vivid
    python: '2.7'
  - os: linux
    dist: Xenial
    python: '2.7'

cache: pip
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install git wget default-jre python-setuptools python-pip  python-dev python-numpy  python-scipy python-matplotlib python-pandas python-imaging python-setuptools unzip ghostscript make gcc g++ zlib1g-dev zlib1g -y

install: python setup.py install
script:
  - haystack_pipeline -help




